In [ ]:
import requests
import urllib.parse
from constants import HEADERS
import pandas as pd
from datetime import datetime

url = 'https://stats.nba.com/stats/drafthistory'
params = {
    'College': '',
    'LeagueID': '00',
    'OverallPick': '',
    'RoundNum': '',
    'RoundPick': '',
    'Season': '',
    'TeamID': '0',
    'TopX': '',
}
params_str = urllib.parse.urlencode(params, safe=":+")
response = requests.get(url=url, params=params_str, headers=HEADERS).json()
df = pd.json_normalize(response, 'resultSets')
df = pd.DataFrame(df["rowSet"][0], columns=df["headers"][0])

In [11]:
df

,PERSON_ID,PLAYER_NAME,SEASON,ROUND_NUMBER,ROUND_PICK,OVERALL_PICK,DRAFT_TYPE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,ORGANIZATION,ORGANIZATION_TYPE,PLAYER_PROFILE_FLAG
0,1642258,Zaccharie Risacher,2024,1,1,1,Draft,1610612737,Atlanta,Hawks,ATL,JL Bourg (France),Other Team/Club,1
1,1642259,Alex Sarr,2024,1,2,2,Draft,1610612764,Washington,Wizards,WAS,Perth Wildcats (Australia),Other Team/Club,1
2,1642263,Reed Sheppard,2024,1,3,3,Draft,1610612745,Houston,Rockets,HOU,Kentucky,College/University,1
3,1642264,Stephon Castle,2024,1,4,4,Draft,1610612759,San Antonio,Spurs,SAS,Connecticut,College/University,1
4,1641842,Ronald Holland II,2024,1,5,5,Draft,1610612765,Detroit,Pistons,DET,Ignite (G League),Other Team/Club,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8310,78402,Gene Vance,1947,0,0,0,Draft,1610610025,Chicago,Stags,CHS,Illinois,College/University,1
8311,79295,Bob Alamo,1947,0,0,0,Draft,1610610031,Pittsburgh,Ironmen,PIT,Santa Clara,College/University,0
8312,79315,Bill Burke,1947,0,0,0,Draft,1610610036,Washington,Capitols,WAS,St. Mary's (MD),College/University,0
8313,79284,Jack Stone,1947,0,0,0,Draft,1610610025,Chicago,Stags,CHS,Kansas State,College/University,0
8314,76773,Harry Gallatin,1947,0,0,0,Draft,1610610024,Baltimore,Bullets,BAL,Truman State,College/University,1

In [3]:
date_string = datetime.now().strftime("%Y%m%d")
df.to_csv(f'../data/alltime_draft_{date_string}.csv')

Player Season requesting

In [1]:
from player_season import PlayerSeasonRequester
import os
RequestObj = PlayerSeasonRequester()

In [2]:
start_year = 2024
end_year = 2025
years = range(start_year, end_year)
df_list = []
base_dir = '../data'
for year in years:
    season_end_year = year + 1
    season_id = f'{year}-{str(season_end_year)[-2:]}'
    RequestObj.populate_season(season_id=season_id)
    tmp_df = RequestObj.df
    tmp_df['season_id'] = season_id
    tmp_df['season_year_start'] = year
    df_list.append(RequestObj.df)
    outfile = '/'.join([base_dir, 'player_season_stats', f'{season_id}.csv'])
    # tmp_df.to_csv(outfile)
    print('completed {season_id} season'.format(season_id=season_id))

completed 2024-25 season

In [8]:
import pandas as pd
df_tot = pd.concat(df_list)

Here we need to add a column that indicates what year it is for the player (e.g. 1, 2, 3, etc...)

In [15]:
draft_df = pd.read_csv('D://Andy/python/nba_analysis_app/data/alltime_draft.csv')
draft_df.rename(columns={'PERSON_ID': 'PLAYER_ID'}, inplace=True)

In [42]:
# joine dataframes and calculate player year
combo_df = pd.merge(df_tot, draft_df, on=['PLAYER_ID'], how='left')
combo_df['player_year'] = (combo_df.season_year_start - combo_df.SEASON) + 1
logic = (combo_df.player_year == 1) & (combo_df.TEAM_ID_x != combo_df.TEAM_ID_y)
combo_df.loc[logic, 'TEAM_ID_x'] = combo_df.loc[logic, 'TEAM_ID_y']
combo_df.loc[logic, 'TEAM_ABBREVIATION_x'] = combo_df.loc[logic, 'TEAM_ABBREVIATION_y']

In [44]:
combo_df.to_csv('D:/Andy/python/nba_analysis_app/data/1989-21_combo.csv')

### All NBA Requesting

In [3]:
from allnba_retr import allnba_retr

allnba_df = allnba_retr()
allnba_df

                      PLAYER                     TEAM   SEASON  NTEAM
0      Giannis Antetokounmpo          Milwaukee Bucks  2024-25      1
1    Shai Gilgeous-Alexander    Oklahoma City Thunder  2024-25      1
2               Nikola Jokić           Denver Nuggets  2024-25      1
3           Donovan Mitchell      Cleveland Cavaliers  2024-25      1
4               Jayson Tatum           Boston Celtics  2024-25      1
..                       ...                      ...      ...    ...
970        Frankie Baumholtz         Cleveland Rebels  1946-47      2
971          Ernie Calverley  Providence Steamrollers  1946-47      2
972            Chick Halbert            Chicago Stags  1946-47      2
973               John Logan        St. Louis Bombers  1946-47      2
974             Fred Scolari      Washington Capitols  1946-47      2

[975 rows x 4 columns]

In [4]:
allnba_df.to_csv('../data/allnba_players.csv', index=False)

In [1]:
from player_season import PlayerSeasonRequester
import os
RequestObj = PlayerSeasonRequester()

In [2]:
year = 2024
season_end_year = year + 1
season_id = f'{year}-{str(season_end_year)[-2:]}'
RequestObj.populate_season(season_id=season_id)
tmp_df = RequestObj.df
tmp_df['season_id'] = season_id
tmp_df['season_year_start'] = year

In [4]:
tmp_df[tmp_df['PLAYER_NAME'].str.strip().str.lower() == 'ochai agbaji']

Empty DataFrame
Columns: [PLAYER_ID, PLAYER_NAME, NICKNAME, TEAM_ID, TEAM_ABBREVIATION, AGE, GP, W, L, W_PCT, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, TOV, STL, BLK, BLKA, PF, PFD, PTS, PLUS_MINUS, NBA_FANTASY_PTS, DD2, TD3, WNBA_FANTASY_PTS, GP_RANK, W_RANK, L_RANK, W_PCT_RANK, MIN_RANK, FGM_RANK, FGA_RANK, FG_PCT_RANK, FG3M_RANK, FG3A_RANK, FG3_PCT_RANK, FTM_RANK, FTA_RANK, FT_PCT_RANK, OREB_RANK, DREB_RANK, REB_RANK, AST_RANK, TOV_RANK, STL_RANK, BLK_RANK, BLKA_RANK, PF_RANK, PFD_RANK, PTS_RANK, PLUS_MINUS_RANK, NBA_FANTASY_PTS_RANK, DD2_RANK, TD3_RANK, WNBA_FANTASY_PTS_RANK, TEAM_COUNT, season_id, season_year_start]
Index: []

[0 rows x 69 columns]